// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ACTORMOVE_MESSAGE_H_
#define FLATBUFFERS_GENERATED_ACTORMOVE_MESSAGE_H_

#include "flatbuffers/flatbuffers.h"

#include "vector_generated.h"

namespace message {

struct ActorMove;

struct ActorMove FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_POSITION = 4
  };
  const Vector *Position() const {
    return GetStruct<const Vector *>(VT_POSITION);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Vector>(verifier, VT_POSITION) &&
           verifier.EndTable();
  }
};

struct ActorMoveBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_Position(const Vector *Position) {
    fbb_.AddStruct(ActorMove::VT_POSITION, Position);
  }
  explicit ActorMoveBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ActorMoveBuilder &operator=(const ActorMoveBuilder &);
  flatbuffers::Offset<ActorMove> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ActorMove>(end);
    return o;
  }
};

inline flatbuffers::Offset<ActorMove> CreateActorMove(
    flatbuffers::FlatBufferBuilder &_fbb,
    const Vector *Position = 0) {
  ActorMoveBuilder builder_(_fbb);
  builder_.add_Position(Position);
  return builder_.Finish();
}

inline const message::ActorMove *GetActorMove(const void *buf) {
  return flatbuffers::GetRoot<message::ActorMove>(buf);
}

inline const message::ActorMove *GetSizePrefixedActorMove(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<message::ActorMove>(buf);
}

inline bool VerifyActorMoveBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<message::ActorMove>(nullptr);
}

inline bool VerifySizePrefixedActorMoveBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<message::ActorMove>(nullptr);
}

inline void FinishActorMoveBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<message::ActorMove> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedActorMoveBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<message::ActorMove> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace message

#endif  // FLATBUFFERS_GENERATED_ACTORMOVE_MESSAGE_H_
