// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESSAGE_MESSAGE_H_
#define FLATBUFFERS_GENERATED_MESSAGE_MESSAGE_H_

#include "flatbuffers/flatbuffers.h"

namespace Message {

struct Vec;

struct Actor;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec FLATBUFFERS_FINAL_CLASS {
 private:
  float X_;
  float Y_;

 public:
  Vec() {
    memset(this, 0, sizeof(Vec));
  }
  Vec(float _X, float _Y)
      : X_(flatbuffers::EndianScalar(_X)),
        Y_(flatbuffers::EndianScalar(_Y)) {
  }
  float X() const {
    return flatbuffers::EndianScalar(X_);
  }
  float Y() const {
    return flatbuffers::EndianScalar(Y_);
  }
};
FLATBUFFERS_STRUCT_END(Vec, 8);

struct Actor FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_POSITION = 4
  };
  const Vec *Position() const {
    return GetStruct<const Vec *>(VT_POSITION);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Vec>(verifier, VT_POSITION) &&
           verifier.EndTable();
  }
};

struct ActorBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_Position(const Vec *Position) {
    fbb_.AddStruct(Actor::VT_POSITION, Position);
  }
  explicit ActorBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ActorBuilder &operator=(const ActorBuilder &);
  flatbuffers::Offset<Actor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Actor>(end);
    return o;
  }
};

inline flatbuffers::Offset<Actor> CreateActor(
    flatbuffers::FlatBufferBuilder &_fbb,
    const Vec *Position = 0) {
  ActorBuilder builder_(_fbb);
  builder_.add_Position(Position);
  return builder_.Finish();
}

inline const Message::Actor *GetActor(const void *buf) {
  return flatbuffers::GetRoot<Message::Actor>(buf);
}

inline const Message::Actor *GetSizePrefixedActor(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<Message::Actor>(buf);
}

inline bool VerifyActorBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Message::Actor>(nullptr);
}

inline bool VerifySizePrefixedActorBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Message::Actor>(nullptr);
}

inline void FinishActorBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Message::Actor> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedActorBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Message::Actor> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Message

#endif  // FLATBUFFERS_GENERATED_MESSAGE_MESSAGE_H_
